name: functions 
on: push
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo ${{ contains('hello', 'll') }}
          echo ${{ startsWith('hello', 'he') }}
          echo ${{ endsWith('hello', 'lo') }}
          echo ${{ format('hello {0} {1} {2}}', 'World', '!', '!') }}
