name: functions 
on: push
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo ${{ contains()}}
          echo ${{startsWith()}}
          echo ${{endsWith()}}
          echo ${{format('hello {0} {1} {2}}', 'World', '!', '!')}}
