name: matrix
on: push
jobs:
  checking-node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
    runs-on: ${{matrix.os}}
    steps:
      - name: check node version
        run: node -v
